// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4zwzgR_JZzChe7WMHIYgpx6GNuhd76w0',
    appId: '1:46362122322:web:0ceda9778f000fc6f6a78b',
    messagingSenderId: '46362122322',
    projectId: 'chat-app-9114c',
    authDomain: 'chat-app-9114c.firebaseapp.com',
    storageBucket: 'chat-app-9114c.firebasestorage.app',
    measurementId: 'G-9PFJ017ZL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHGtpLd5X57jEwY7BxJQYUkps_ieJPq4Q',
    appId: '1:46362122322:android:91c36c3c84b8694bf6a78b',
    messagingSenderId: '46362122322',
    projectId: 'chat-app-9114c',
    storageBucket: 'chat-app-9114c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARQn1ErBKIX5eT83XyupNSVXoVDWvMZP4',
    appId: '1:46362122322:ios:d7d0e7c8de358c6bf6a78b',
    messagingSenderId: '46362122322',
    projectId: 'chat-app-9114c',
    storageBucket: 'chat-app-9114c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARQn1ErBKIX5eT83XyupNSVXoVDWvMZP4',
    appId: '1:46362122322:ios:d7d0e7c8de358c6bf6a78b',
    messagingSenderId: '46362122322',
    projectId: 'chat-app-9114c',
    storageBucket: 'chat-app-9114c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4zwzgR_JZzChe7WMHIYgpx6GNuhd76w0',
    appId: '1:46362122322:web:01b3c58a98413ddef6a78b',
    messagingSenderId: '46362122322',
    projectId: 'chat-app-9114c',
    authDomain: 'chat-app-9114c.firebaseapp.com',
    storageBucket: 'chat-app-9114c.firebasestorage.app',
    measurementId: 'G-8QX980B8SE',
  );
}
